name: "build nixos image"

on:
  push:

jobs:
  build-img:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |-
          system-features = nixos-test benchmark big-parallel kvm
          experimental-features = nix-command flakes
    - run: nix build .#packages.x86_64-linux.img
    - run: du -sh result/nixos.img
