name: "build nixos image"

on:
  push:

jobs:
  build-img:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |-
          system-features = nixos-test benchmark big-parallel kvm
          experimental-features = nix-command flakes
    - run: nix build .#packages.${{ matrix.arch }}-linux.img
    - run: du -sh result/nixos.img
    - run: mv result/nixos.img nixos-${{ matrix.arch }}.img
    - name: archive built-image artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nixos-${{ matrix.arch }}-lima-img
        path: |
          nixos-${{ matrix.arch }}.img
